src/Avatar/Avatar.js
src/Dropdown/README.md
src/Table/README.md
src/Table/Table.js
src/Table/__tests__/Table.test.js

* @jira improve components
* @jira improve components
* @jira improve components
* @jira improve components

@jira improve components (#51)

---

src/Checkboxes/Checkboxes.js

Fixed undefined event, destructuring issue.

BZ2-266 fixed event was undefined

---

packages/More/src/MoreContent/MoreContent.js

BZ-XX classname fix

---

packages/Select/__tests__/__snapshots__/Select.test.tsx.snap
packages/Select/src/index.tsx

BZ2-275 select default option not selectable

---

packages/DraftEditor/src/index.tsx
packages/DraftEditor/stories/DraftEditor.stories.tsx

onchange event format added

---

packages/DraftEditor/src/index.tsx
packages/DraftEditor/stories/DraftEditor.stories.tsx

Be enable to pass a initial value to init editor

initial value added

---

packages/Multiselect/src/index.tsx

Added necessary on change event in input inside multiselect component.

onchange added in mutltiselect

---

package.json
packages/Multiselect/package-lock.json
packages/Multiselect/package.json
packages/Multiselect/src/index.tsx
packages/Multiselect/stories/Multiselect.stories.tsx

Added use effect to update data when new one is receive.

re render when retrieve new data

---

packages/FileUpload/__tests__/__snapshots__/FileUpload.test.tsx.snap
packages/FileUpload/src/index.tsx

Updated file upload to have correct divs and classes

BZ2-577 @jira file upload updated

---

.storybook/css/blaze-ui.css
package-lock.json
package.json
packages/Badge/__tests__/Badge.test.tsx
packages/Badge/src/index.tsx
packages/Badge/stories/Badge.stories.tsx
packages/FileUpload/__tests__/__snapshots__/FileUpload.test.tsx.snap
packages/Utils/src/removeExtraSpaces/index.tsx

Updated Badge component to include badges for page builder (they use icon plus name of the type of icon). Refactored of <a> tag to prevent browser from using a router different than the application. Tests and documentation updated.

Bz2 badge colours

---

packages/FileUpload/__tests__/FileUpload.test.tsx
packages/FileUpload/__tests__/__snapshots__/FileUpload.test.tsx.snap
packages/FileUpload/package.json
packages/FileUpload/src/DocumentIcon/index.tsx
packages/FileUpload/src/FileList/index.tsx
packages/FileUpload/src/index.tsx
packages/FileUpload/stories/FileUpload.stories.tsx

Bz2 577/media upload updates

---

packages/FileUpload/src/index.tsx

on change called on drop files

---

packages/Modal/src/index.tsx

passed classname

---

packages/More/src/index.tsx

stop propagation in more menu

---

packages/Autocomplete/__tests__/Autocomplete.test.tsx
packages/Autocomplete/__tests__/__snapshots__/Autocomplete.test.tsx.snap
packages/Avatar/__tests__/__snapshots__/Avatar.test.tsx.snap
packages/Button/__tests__/__snapshots__/Button.test.tsx.snap
packages/ButtonSelect/__tests__/__snapshots__/ButtonSelect.test.tsx.snap
packages/Chips/__tests__/__snapshots__/Chips.test.tsx.snap
packages/Drawer/__tests__/__snapshots__/Drawer.test.tsx.snap
packages/FileUpload/__tests__/__snapshots__/FileUpload.test.tsx.snap
packages/Input/__tests__/__snapshots__/Input.test.tsx.snap
packages/Loader/__tests__/__snapshots__/Loader.test.tsx.snap
packages/More/__tests__/__snapshots__/More.test.tsx.snap
packages/More/src/MoreContent/MoreContent.tsx
packages/Multiselect/src/index.tsx
packages/RadioButton/__tests__/__snapshots__/RadioButton.test.tsx.snap
packages/Select/__tests__/__snapshots__/Select.test.tsx.snap
packages/Tab/__tests__/__snapshots__/Tab.test.tsx.snap
packages/Table/__tests__/__snapshots__/Table.test.tsx.snap

fix multiselect error input

---

packages/Modal/src/ModalFooter/ModalFooter.tsx

Changed Button modifier for delete type button

BZ2-588 @JIRA Changed modifier for delete button + adjust tests

---

.storybook/css/blaze-ui.css
packages/FileUpload/__tests__/__snapshots__/FileUpload.test.tsx.snap
packages/FileUpload/package.json
packages/FileUpload/src/FileList/index.tsx
packages/FileUpload/src/index.tsx
packages/FileUpload/stories/FileUpload.stories.tsx

Added title, alt text and caption inputs when uploading images with debounce to minimise the number of times data is sent to parent component.

Bz2 556 extend image settings

---

package-lock.json
packages/Table/__tests__/__snapshots__/Table.test.tsx.snap
packages/Table/src/index.tsx
packages/Table/stories/Table.stories.tsx

Updated css for tables (same branch as old BZ2-583/Table issues but with snapshot issue resolved)

Bz2 583/table issues 

---

package-lock.json
package.json
packages/More/__tests__/More.test.tsx
packages/More/__tests__/__snapshots__/More.test.tsx.snap
packages/More/package-lock.json
packages/More/src/MoreAvatar/MoreAvatar.tsx
packages/More/src/MoreContent/MoreContent.tsx
packages/More/src/index.tsx
packages/More/stories/More.stories.tsx
packages/Utils/__tests__/removeExtraSpaces/index.test.tsx

- MoreMenu will not display overlay anymore when clicked from a Table component (needs update on blaze)
- Created a reference so that you can close the MoreMenu when clicking outside when no overlay is displayed

Bz2 598/table more menu refinements

---

packages/Multiselect/README.md
packages/Multiselect/__tests__/Multiselect.test.tsx
packages/Multiselect/__tests__/__snapshots__/Multiselect.test.tsx.snap
packages/Multiselect/src/index.tsx
packages/Multiselect/stories/Multiselect.stories.tsx

Updated multi select to allow for multiple options to arrive and not override each other

Bz2 667/multi select update

---

package-lock.json
packages/DraftEditor/package.json
packages/DraftEditor/src/index.tsx
packages/Multiselect/src/index.tsx
packages/Multiselect/stories/Multiselect.stories.tsx

Updated multi select to handle disabling of checkboxes when limit of items has been reached, updated DraftEditor based on @Arcoders  request.

BZ2-632 updated multi to handle disabling when limit reached

---

package-lock.json
package.json
packages/FileUpload/src/index.tsx

Updated shallow copy to deep copy on handeInputChange function.
Auto eslint changes.

BZ2-678/ @jira fix bug

---

packages/Modal/__tests__/Modal.test.tsx
packages/Modal/src/constants.tsx
packages/Modal/src/index.tsx

Bz2 756/modal esc

---

.vscode/settings.json
packages/Checkboxes/src/index.tsx

* set name for checkbox input & update vscode settings
* update vscode settings for tslint

set name for checkbox input & update vscode settings (#175)

---

packages/Blaze-ui/src/main.scss
packages/Blaze-ui/src/module/_range-slider.scss
packages/RangeSlider/.npmignore
packages/RangeSlider/README.md
packages/RangeSlider/__tests__/RangeSlider.test.tsx
packages/RangeSlider/__tests__/__snapshots__/RangeSlider.test.tsx.snap
packages/RangeSlider/package.json
packages/RangeSlider/src/index.tsx
packages/RangeSlider/stories/RangeSlider.stories.tsx

new component Range Slider

---

packages/Blaze-ui/src/main.scss
packages/Blaze-ui/src/module/_range-slider.scss
packages/RangeSlider/.npmignore
packages/RangeSlider/README.md
packages/RangeSlider/__tests__/RangeSlider.test.tsx
packages/RangeSlider/__tests__/__snapshots__/RangeSlider.test.tsx.snap
packages/RangeSlider/package.json
packages/RangeSlider/src/index.tsx
packages/RangeSlider/stories/RangeSlider.stories.tsx

* new component Range Slider
* some more tests
* corrected tests
* parameters optional

new component Range Slider (#182)

---

packages/Blaze-ui/src/main.scss
packages/Blaze-ui/src/module/_range-slider.scss
packages/RangeSlider/.npmignore
packages/RangeSlider/README.md
packages/RangeSlider/__tests__/RangeSlider.test.tsx
packages/RangeSlider/__tests__/__snapshots__/RangeSlider.test.tsx.snap
packages/RangeSlider/package.json
packages/RangeSlider/src/index.tsx
packages/RangeSlider/stories/RangeSlider.stories.tsx

new component Range slider clean branch

---

packages/More/__tests__/More.test.tsx
packages/More/src/MoreContent/MoreContent.tsx
packages/More/src/index.tsx
packages/Utils/__tests__/ErrorMessage/__snapshots__/index.test.tsx.snap
packages/Utils/__tests__/ErrorMessage/index.test.tsx
packages/Utils/__tests__/uniqueId/index.test.tsx
packages/Utils/src/ErrorMessage/index.tsx

Improve test coverage for MoreMenu component. Still room for improvement. I couldn't find a way to test the functions setToggle and handleOutsideFunction so any ideas or suggestions are welcome.

BZ2-669 @JIRA Create new branch to fix issue with snapshots

---

.typescript/tsconfig.json
.typescript/typings.d.ts
package-lock.json
package.json
packages/Utils/__tests__/customHooks/useInView/index.test.tsx
packages/Utils/package.json
packages/Utils/src/customHooks/index.tsx
packages/Utils/src/customHooks/useInView/index.tsx
packages/Utils/stories/CustomHooks.stories.tsx

- in view hook created and tested

added custom hook inView to use it for lazy loading

---

package-lock.json
packages/Multiselect/__tests__/__snapshots__/Multiselect.test.tsx.snap
packages/Multiselect/src/index.tsx
packages/Multiselect/stories/Multiselect.stories.tsx
packages/RangeFilter/src/index.tsx

add wildcard to multiselect component
https://byte-9.atlassian.net/browse/BZ2-1066

BZ2-1066 @jira add wildcard to multiselect

---

packages/Select/__tests__/__snapshots__/Select.test.tsx.snap
packages/Select/src/index.tsx

Removed the 'please select' option if input is required

BZ2-1005 @JIRA Remove the 'please select' option if input is required

---

packages/Select/__tests__/Select.test.tsx
packages/Select/__tests__/__snapshots__/Select.test.tsx.snap
packages/Select/src/index.tsx

Bz2 1005/select default value fix

---

packages/RangeFilter/src/index.tsx

Fix- Range Filter component doesn't update on first try

@jira Range Filter component fix update

---

packages/Blaze-ui/src/base/_base.scss
packages/Blaze-ui/src/module/_forms.scss
packages/RangeFilter/__tests__/RangeFilter.test.tsx
packages/RangeFilter/__tests__/__snapshots__/RangeFilter.test.tsx.snap
packages/RangeFilter/src/index.tsx
packages/RangeFilter/src/logic.tsx
packages/RangeFilter/stories/RangeFilter.stories.tsx

https://byte-9.atlassian.net/browse/BZ2-1109
Fix rangeFilter to support all browsers using drag and drop

BZ2-1109 @jira fix range filter

---

packages/DraftEditor/src/DraftPlugins/CustomPlugins/LinkControl/LinkControl.tsx
packages/Textarea/src/index.tsx

Text-Block support mailto: links
https://byte-9.atlassian.net/browse/BZ2-1126
Fix Textarea on reset value
https://byte-9.atlassian.net/browse/BZ2-1133

Bz2 1126/update text block

---

package-lock.json
packages/DraftEditor/src/constants/index.tsx
packages/DraftEditor/src/index.tsx
packages/More/__tests__/__snapshots__/More.test.tsx.snap

TextBlock - exclude backspace command

BZ2-1186 @jira TextBlock - exclude backspace command

---

packages/RangeFilter/__tests__/__snapshots__/RangeFilter.test.tsx.snap
packages/RangeFilter/src/index.tsx

Range filter add classNName

---

packages/FileUpload/README.md
packages/FileUpload/__tests__/__snapshots__/FileUpload.test.tsx.snap
packages/FileUpload/src/Actions/index.tsx
packages/FileUpload/src/index.tsx

dynamic button prop in file upload component

dynamic button prop in file upload component

---

package-lock.json
packages/Blaze-ui/src/module/_forms.scss
packages/RangeFilter/__tests__/__snapshots__/RangeFilter.test.tsx.snap
packages/RangeFilter/src/index.tsx
packages/RangeFilter/src/logic.tsx

This pr includes some console.log, is a pr to test a strange case n production

BZ2 range filter test on production

---

packages/RangeFilter/src/logic.tsx

Made a loop to keep getting the widths until they are different values.

intent on Range fix

---

package-lock.json
packages/DraftEditor/src/DraftPlugins/CustomPlugins/HTMLEditor/HTMLEditor.tsx
packages/DraftEditor/src/DraftPlugins/CustomPlugins/ImageControl/ImageControl.tsx
packages/DraftEditor/src/DraftPlugins/CustomPlugins/LinkControl/LinkControl.tsx
packages/DraftEditor/src/DraftPlugins/CustomPlugins/StyleButton/StyleButton.tsx
packages/DraftEditor/src/interfaces/index.tsx

BZ2-XXX/@jira add data-cy draft buttons

---

package-lock.json
packages/Multiselect/__tests__/Multiselect.test.tsx
packages/Multiselect/__tests__/__snapshots__/Multiselect.test.tsx.snap
packages/Multiselect/src/index.tsx

Update logic to build label depending if is chip label or checkbox label.

Bz2 1269/multiselect aditional labels

---

package-lock.json
packages/DraftEditor/src/DraftPlugins/CustomPlugins/index.tsx
packages/DraftEditor/src/index.tsx
packages/DraftEditor/src/interfaces/index.tsx
packages/DraftEditor/stories/DraftEditor.stories.tsx

Remove image on text block element

Bz2 1300/disable image plugin

---

package-lock.json
packages/Checkboxes/src/index.tsx
packages/DraftEditor/src/DraftPlugins/CustomPlugins/LinkControl/Anchor.tsx
packages/DraftEditor/src/DraftPlugins/CustomPlugins/LinkControl/LinkControl.tsx

Draftjs plugin
Fix relative link

BZ2 fix relative links

---

.typescript/typings.d.ts
package-lock.json
packages/Blaze-ui/src/module/_forms.scss
packages/Checkboxes/__tests__/__snapshots__/Checkbox.test.tsx.snap
packages/Checkboxes/src/Checkbox.tsx
packages/Checkboxes/src/index.tsx
packages/Checkboxes/src/interface.ts
packages/Checkboxes/stories/Checkbox.stories.tsx
packages/DateRange/README.md
packages/DateRange/__tests__/DateRange.test.tsx
packages/DateRange/src/index.tsx
packages/DateRange/stories/DateRange.stories.tsx
packages/DraftEditor/package-lock.json
packages/DraftEditor/src/DraftPlugins/CustomPlugins/LinkControl/LinkControl.tsx
packages/DraftEditor/src/index.tsx
packages/FileUpload/__tests__/FileInputs/__snapshots__/FileInputs.test.tsx.snap
packages/Multiselect/__tests__/__snapshots__/Multiselect.test.tsx.snap
packages/Multiselect/src/MultiSelectList.tsx
packages/Select/README.md
packages/Select/__tests__/__snapshots__/Select.test.tsx.snap
packages/Select/src/index.tsx
packages/Select/stories/Select.stories.tsx
packages/Table/__tests__/src/TableBody/__snapshots__/TableBody.test.tsx.snap

https://byte-9.atlassian.net/browse/BZ2-1433
DateRange: update api
Draftjs: Hyperlink auto-focus

BZ2-1433 @jira update DateRange api

---

package-lock.json
packages/Blaze-ui/src/module/_forms.scss
packages/Checkboxes/__tests__/Checkbox.test.tsx
packages/Checkboxes/src/Checkbox.tsx
packages/Checkboxes/src/Label.tsx
packages/Multiselect/__tests__/__snapshots__/Multiselect.test.tsx.snap
packages/Table/__tests__/src/TableBody/__snapshots__/TableBody.test.tsx.snap

Checkbox fixes
https://byte-9.atlassian.net/browse/BZ2-1428

BZ2-1428 @jira fix checkboxes

---

packages/Checkboxes/src/Checkbox.tsx
packages/Multiselect/__tests__/__snapshots__/Multiselect.test.tsx.snap
packages/Multiselect/src/MultiSelectList.tsx
packages/Table/__tests__/src/TableBody/__snapshots__/TableBody.test.tsx.snap

fix cypress

---

packages/More/src/MoreContent/MoreContent.tsx
packages/More/src/index.tsx

Table More Menu Refinement
https://byte-9.atlassian.net/browse/BZ2-648

BZ2-648 @jira fix moreMenu postion

---

package-lock.json
packages/DraftEditor/src/DraftPlugins/CustomPlugins/index.tsx
packages/DraftEditor/src/index.tsx
packages/DraftEditor/src/interfaces/index.tsx

https://byte-9.atlassian.net/browse/BZ2-1438
Remove Embed from Text-block

hide embed code

---

package-lock.json
packages/Utils/src/customHooks/useInView/index.tsx

No need to add an if statement, the polyfill should be added before requiring any other modules and it does the necessary validations

BZ2-1445 @jira fix intersection-observer error

---

packages/Table/__tests__/mocks/index.tsx
packages/Table/__tests__/src/TableHead/SortableCell/SortableCell.test.tsx
packages/Table/__tests__/src/TableHead/TableHead.test.tsx
packages/Table/src/TableHead/SortableCell/SortableCell.tsx
packages/Table/src/TableHead/TableHead.tsx
packages/Table/src/index.tsx
packages/Table/stories/Table.stories.tsx

[JIRA](https://byte-9.atlassian.net/browse/BZ2-1489)
Added label property so that we display a user label if introduced by the client.

BZ2-1489 @JIRA Use label in table header

---

package-lock.json
packages/FileUpload/__tests__/FileInputs/FileInputs.test.tsx
packages/FileUpload/__tests__/FileInputs/__snapshots__/FileInputs.test.tsx.snap
packages/FileUpload/src/FileInputs/index.tsx
packages/FileUpload/src/constants.tsx

[Jira ticket](https://byte-9.atlassian.net/browse/BZ2-1289)
Added hrefUrl input to display.

BZ2-1289/Image-settings-url @jira add href url input

---

package-lock.json
packages/RangeFilter/src/logic.tsx

(Jira ticket)[https://byte-9.atlassian.net/browse/BZ2-1669]
  Fix bug on Ranger filter logic, error related to `eventTouch` let initialization.
**Before**
**After**

BZ2-1669/Slider-mobile-bug @jira change eventTouch constant

---

packages/Input/src/index.tsx

[Jira Ticket](https://byte-9.atlassian.net/browse/BZ2-1697)
Updated the value to be set to handle 0

BZ2-1697/Handle-number-0 @jira update useEffect

---

packages/Badge/README.md
packages/Badge/__tests__/__snapshots__/Badge.test.tsx.snap
packages/Badge/src/index.tsx

[JIRA](https://byte-9.atlassian.net/browse/BZ2-1739)
Add modifier to classname to be able to use other types of badges (for status) in blaze-admin

BZ2-1739 @JIRA Add modifier to classname on span

---

package-lock.json
packages/RangeFilter/src/logic.tsx

[Jira ticket](https://byte-9.atlassian.net/browse/BOATINT-761)
Fixed bug on range filter (drag the max select on a range search filter to be below the minimum and in some cases can become negative value)

BOATINT-761/range-filter-bug @jira fix bug

---

package-lock.json
packages/Input/__tests__/Input.test.tsx
packages/Multiselect/src/MultiSelectList.tsx
packages/RangeFilter/src/logic.tsx

https://github.com/thebyte9/blaze-components-react/pull/393 - Remove unused onItemsRendered logic for multiselect

Release - v0.5.27

---

packages/Input/__tests__/Input.test.tsx
packages/Input/src/index.tsx
packages/Input/stories/Input.stories.tsx

Addresses [BZ2-2061](https://byte-9.atlassian.net/browse/BZ2-2061).

BZ2-2061 - Handle date object in input component

---

packages/Input/__tests__/Input.test.tsx
packages/Input/src/index.tsx
packages/Input/stories/Input.stories.tsx

* Adapt dateTime input component to receive date objects
* Add test

BZ2-2061 - Handle date object in input component (#424)

---

package-lock.json
packages/Checkboxes/src/Checkbox.tsx
packages/Checkboxes/src/index.tsx
packages/Modal/src/index.tsx
packages/Modal/stories/Modal.stories.tsx
packages/Multiselect/__tests__/__snapshots__/Multiselect.test.tsx.snap
packages/Table/__tests__/src/TableBody/__snapshots__/TableBody.test.tsx.snap

Fix Modal and Checkboxes
https://byte-9.atlassian.net/browse/BZ2-2006

fix overlay

---

packages/DateTimeInput/README.md
packages/DateTimeInput/__tests__/__snapshots__/DateTimeInput.test.tsx.snap
packages/DateTimeInput/src/constants.tsx
packages/DateTimeInput/src/index.tsx

https://github.com/thebyte9/blaze-components-react/pull/434 - DateTimeInput updates

Release - v0.6.1

---

packages/Multiselect/__tests__/Multiselect.test.tsx
packages/Multiselect/src/index.tsx
packages/Multiselect/stories/Multiselect.stories.tsx

Addresses [BZ2-2123](https://byte-9.atlassian.net/browse/BZ2-2123)

BZ2-2123 - Clear multiselect input upon checking a checkbox
